In [1]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [3]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression 

In [4]:
steps =[("standard_scaler", StandardScaler()),
       ("classifier",LogisticRegression())]

In [5]:
steps

[('standard_scaler', StandardScaler()), ('classifier', LogisticRegression())]

In [6]:
pipe = Pipeline(steps)

In [7]:
from sklearn import set_config

In [8]:
set_config(display = "diagram")

In [9]:
pipe

Pipeline(steps=[('standard_scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [11]:
from sklearn.datasets import make_classification
X,y = make_classification(n_samples = 10000)

In [12]:
X.shape

(10000, 20)

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size =0.33,random_state= 42)

In [19]:
X_train

array([[-9.84821434e-01, -3.09449561e-01,  9.23963841e-02, ...,
        -2.56140923e+00,  1.33058085e+00, -5.10274066e-01],
       [ 2.05617462e-01,  1.41387904e+00, -2.03063156e+00, ...,
         2.17652881e+00, -1.72208242e+00,  1.30533069e+00],
       [ 6.09209865e-02, -1.09094817e+00, -1.46392839e+00, ...,
         6.37557241e-01, -6.50402549e-01,  6.00086454e-01],
       ...,
       [-2.45706691e-03, -4.21387741e-01,  1.70760166e+00, ...,
         8.25311668e-01,  1.11633785e+00, -2.04180984e+00],
       [-2.77500605e-01, -1.34181199e-01, -1.20349504e+00, ...,
         1.67337091e+00, -1.39837532e+00,  6.69869296e-01],
       [-4.64071340e-01, -1.41105969e-01,  1.10515496e+00, ...,
         4.85583002e-01, -1.36683937e+00,  1.31341695e+00]])

In [20]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('standard_scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [21]:
y_pred = pipe.predict(X_test)
y_pred

array([0, 1, 1, ..., 0, 1, 1])

In [23]:
X_test

array([[-0.40365398, -0.85269891, -0.30125915, ...,  0.05135419,
         0.85605252,  0.34766589],
       [ 0.14592842,  0.4512024 ,  1.54774356, ..., -1.38251615,
        -1.12088029, -0.33095452],
       [-0.24221688,  0.22609586,  1.77567123, ..., -0.20599427,
        -0.2368508 , -0.67226235],
       ...,
       [ 0.56744563, -1.56349713, -2.12128125, ...,  0.81281693,
        -0.58187326, -1.49562045],
       [-0.06319607,  0.07816745, -1.99470029, ...,  0.0428584 ,
         1.2890995 , -1.00578337],
       [ 0.07470356, -1.65754532, -0.19081005, ...,  0.79581992,
        -0.12381022, -1.14951286]])

In [24]:
#new program 
from sklearn.decomposition import PCA
from sklearn.svm import SVC

In [25]:
steps=[("scaling", StandardScaler()),("PCA", PCA(n_components =3)),("SVC",SVC())]

In [27]:
pipe2 = Pipeline(steps)

In [28]:
pipe2

Pipeline(steps=[('scaling', StandardScaler()), ('PCA', PCA(n_components=3)),
                ('SVC', SVC())])

In [29]:
pipe2.fit(X_train,y_train)

Pipeline(steps=[('scaling', StandardScaler()), ('PCA', PCA(n_components=3)),
                ('SVC', SVC())])

In [30]:
y_pred = pipe2.predict(X_test)
y_pred

array([1, 0, 1, ..., 0, 1, 1])

In [31]:
from sklearn.impute import SimpleImputer

In [37]:
import numpy as np
numeric_processor=Pipeline(
    steps=[("imputation_mean", SimpleImputer(missing_values=np.nan,strategy ="mean")),
           ("scaler",StandardScaler())]
)

In [38]:
numeric_processor

Pipeline(steps=[('imputation_mean', SimpleImputer()),
                ('scaler', StandardScaler())])

In [41]:
from sklearn.preprocessing import OneHotEncoder
categorical_processor=Pipeline(
    steps=[("imputation_constant",SimpleImputer(fill_value="missing",strategy="constant")),
    ("onehot",OneHotEncoder(handle_unknown="ignore"))]
)

In [43]:
categorical_processor

Pipeline(steps=[('imputation_constant',
                 SimpleImputer(fill_value='missing', strategy='constant')),
                ('onehot', OneHotEncoder(handle_unknown='ignore'))])

In [44]:
from sklearn.compose import ColumnTransformer

In [47]:
preprocessor=ColumnTransformer(
    [("categorical",categorical_processor,["gender","City"]),
    ("numerical",numeric_processor,["age","height"])]
)

In [48]:
preprocessor

ColumnTransformer(transformers=[('categorical',
                                 Pipeline(steps=[('imputation_constant',
                                                  SimpleImputer(fill_value='missing',
                                                                strategy='constant')),
                                                 ('onehot',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['gender', 'City']),
                                ('numerical',
                                 Pipeline(steps=[('imputation_mean',
                                                  SimpleImputer()),
                                                 ('scaler', StandardScaler())]),
                                 ['age', 'height'])])

In [49]:
from sklearn.pipeline import make_pipeline

In [51]:
pipe=make_pipeline(preprocessor,LogisticRegression())

In [52]:
pipe

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('categorical',
                                                  Pipeline(steps=[('imputation_constant',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['gender', 'City']),
                                                 ('numerical',
                                                  Pipeline(steps=[('imputation_mean',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['age', 'height'])])),
                ('logisticregression', LogisticRegression())])